server:
  port: 80
  servlet:
    context-path: /

    
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SJK
    password: java
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  security:
    user:
      name: username
      password: password
  
  messages:
#메세지 등록 messages라는 파일이름을 등록
    basename: message
    
  devtools:
    livereload:
      enabled: true
  
logging:
  level:
    '[org.springframework]': DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
    